// Generates index.d.ts and index.d.mts from index.json.
//
// parser.js only runs inside a browser (it scrapes the loc.gov ISO 639-2 table
// through the DOM), so the types are built from the committed index.json
// instead. That keeps the union of keys and the data file impossible to
// desync: both come from the very same object.
//
// Two declaration files are emitted because the package ships two entry
// points: `require('iso639-codes')` resolves to index.json and needs the
// `export =` form, while `import codes from 'iso639-codes'` resolves to
// index.mjs and needs a real ESM declaration. Shipping only the CommonJS one
// makes `import { codes }` fail to typecheck under node16/nodenext.
//
// Usage: npm run build:types

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const dataFile = path.join(root, 'index.json')
const outputFile = path.join(root, 'index.d.ts')
const moduleOutputFile = path.join(root, 'index.d.mts')

const banner = '// Generated by scripts/build-types.js from index.json. Do not edit by hand.'

const quote = (value) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

const keysOf = (codes) => {
  const keys = Object.keys(codes)

  if (keys.length === 0) {
    throw new Error('index.json is empty, refusing to generate declarations')
  }

  return keys
}

// Indented one extra level in the CommonJS build, where the members live
// inside `declare namespace codes`.
const fields = (indent) => [
  `${indent}/** English name of the language. Always equal to the key of the entry. */`,
  `${indent}name: string`,
  `${indent}/** Every English name the ISO 639-2 registry lists for the entry. */`,
  `${indent}names: string[]`,
  `${indent}/** ISO 639-2 (three letters) code. */`,
  `${indent}'iso639-2': string`,
  `${indent}/** ISO 639-1 (two letters) code, \`null\` when the language has none. */`,
  `${indent}'iso639-1': string | null`
]

const buildTypes = (codes) => {
  const union = keysOf(codes).map((key) => `\t\t| ${quote(key)}`).join('\n')

  return [
    banner,
    '',
    'declare namespace codes {',
    '\tinterface Iso639Code {',
    ...fields('\t\t'),
    '\t}',
    '',
    '\ttype Iso639Key =',
    union,
    '}',
    '',
    'declare const codes: Record<codes.Iso639Key, codes.Iso639Code>',
    '',
    'export = codes',
    ''
  ].join('\n')
}

const buildModuleTypes = (codes) => {
  const union = keysOf(codes).map((key) => `\t| ${quote(key)}`).join('\n')

  return [
    banner,
    'export interface Iso639Code {',
    ...fields('\t'),
    '}',
    '',
    'export type Iso639Key =',
    union,
    '',
    'declare const codes: Record<Iso639Key, Iso639Code>',
    '',
    'export default codes',
    'export { codes }',
    ''
  ].join('\n')
}

const main = () => {
  const codes = JSON.parse(fs.readFileSync(dataFile, 'utf8'))

  fs.writeFileSync(outputFile, buildTypes(codes))
  fs.writeFileSync(moduleOutputFile, buildModuleTypes(codes))
  console.log(`index.d.ts and index.d.mts: ${Object.keys(codes).length} keys`)
}

if (require.main === module) {
  main()
}

module.exports = { buildTypes, buildModuleTypes }
