// Generates index.mjs from index.json.
//
// The data is inlined instead of imported: `import codes from './index.json'`
// needs import attributes (`with { type: 'json' }`), which are not available on
// every runtime/bundler, and `createRequire` only works on Node. An inlined
// object literal is plain ESM and runs anywhere without flags.
//
// Usage: npm run build:esm

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const dataFile = path.join(root, 'index.json')
const outputFile = path.join(root, 'index.mjs')

const buildEsm = (codes) => {
  const keys = Object.keys(codes)

  if (keys.length === 0) {
    throw new Error('index.json is empty, refusing to generate index.mjs')
  }

  const entries = keys
    .map((key) => `\t${JSON.stringify(key)}: ${JSON.stringify(codes[key])}`)
    .join(',\n')

  return [
    '// Generated by scripts/build-esm.js from index.json. Do not edit by hand.',
    '',
    'const codes = {',
    entries,
    '}',
    '',
    'export default codes',
    'export { codes }',
    ''
  ].join('\n')
}

const main = () => {
  const codes = JSON.parse(fs.readFileSync(dataFile, 'utf8'))
  const output = buildEsm(codes)

  fs.writeFileSync(outputFile, output)
  console.log(`index.mjs: ${Object.keys(codes).length} keys`)
}

if (require.main === module) {
  main()
}

module.exports = { buildEsm }
