// Generates index.d.ts from index.json.
//
// parser.js only runs inside a browser (it scrapes the loc.gov ISO 639-2 table
// through the DOM), so the types are built from the committed index.json
// instead. That keeps the union of keys and the data file impossible to
// desync: both come from the very same object.
//
// Usage: npm run build:types

const fs = require('fs')
const path = require('path')

const root = path.join(__dirname, '..')
const dataFile = path.join(root, 'index.json')
const outputFile = path.join(root, 'index.d.ts')

const quote = (value) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

const buildTypes = (codes) => {
  const keys = Object.keys(codes)

  if (keys.length === 0) {
    throw new Error('index.json is empty, refusing to generate index.d.ts')
  }

  const union = keys.map((key) => `\t\t| ${quote(key)}`).join('\n')

  return [
    '// Generated by scripts/build-types.js from index.json. Do not edit by hand.',
    '',
    'declare namespace codes {',
    '\tinterface Iso639Code {',
    '\t\t/** English name of the language. Always equal to the key of the entry. */',
    '\t\tname: string',
    '\t\t/** Every English name the ISO 639-2 registry lists for the entry. */',
    '\t\tnames: string[]',
    '\t\t/** ISO 639-2 (three letters) code. */',
    "\t\t'iso639-2': string",
    '\t\t/** ISO 639-1 (two letters) code, `null` when the language has none. */',
    "\t\t'iso639-1': string | null",
    '\t}',
    '',
    '\ttype Iso639Key =',
    union,
    '}',
    '',
    'declare const codes: Record<codes.Iso639Key, codes.Iso639Code>',
    '',
    'export = codes',
    ''
  ].join('\n')
}

const main = () => {
  const codes = JSON.parse(fs.readFileSync(dataFile, 'utf8'))
  const output = buildTypes(codes)

  fs.writeFileSync(outputFile, output)
  console.log(`index.d.ts: ${Object.keys(codes).length} keys`)
}

if (require.main === module) {
  main()
}

module.exports = { buildTypes }
